# Generated by Django 5.2.4 on 2025-07-15 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=20)),
                ('pdesc', models.CharField(max_length=20)),
                ('pprice', models.CharField(max_length=20)),
                ('pimg', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
