# Generated by Django 5.2.4 on 2025-07-17 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backenddb', '0002_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='pimg',
            field=models.ImageField(blank=True, null=True, upload_to='product_img/'),
        ),
    ]
