# Generated by Django 5.2.4 on 2025-07-25 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backenddb', '0003_alter_products_pimg'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderConfirm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=20)),
                ('lname', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=20)),
                ('zipCode', models.CharField(max_length=20)),
                ('mobile', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=20)),
                ('shipDifferentAddress', models.CharField(max_length=20)),
                ('orderNotes', models.CharField(max_length=20)),
            ],
        ),
    ]
