# Generated by Django 5.2.4 on 2025-07-28 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backenddb', '0004_orderconfirm'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderconfirm',
            name='payment_method',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
