# Generated by Django 5.2.4 on 2025-07-28 04:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backenddb', '0006_orderconfirm_pid_orderconfirm_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderconfirm',
            name='pid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backenddb.cart'),
        ),
    ]
