# Generated by Django 5.2.4 on 2025-07-28 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backenddb', '0008_alter_orderconfirm_pid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='pid',
            new_name='pid_id',
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='uid',
            new_name='uid_id',
        ),
    ]
