# Generated by Django 5.2.4 on 2025-07-28 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backenddb', '0009_rename_pid_cart_pid_id_rename_uid_cart_uid_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='pid_id',
            new_name='pid',
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='uid_id',
            new_name='uid',
        ),
    ]
