# Generated by Django 5.2.4 on 2025-07-28 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backenddb', '0010_rename_pid_id_cart_pid_rename_uid_id_cart_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderconfirm',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
