# Generated by Django 5.2.4 on 2025-07-28 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backenddb', '0011_orderconfirm_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderconfirm',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
