# Generated by Django 5.2.4 on 2025-08-04 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backenddb', '0012_alter_orderconfirm_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderconfirm',
            name='total',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
