# Generated by Django 5.2.4 on 2025-08-04 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backenddb', '0014_alter_orderconfirm_pid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderconfirm',
            name='pid',
        ),
    ]
