# Generated by Django 5.2.4 on 2025-08-18 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backenddb', '0015_remove_orderconfirm_pid'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='pstock',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
