# Generated by Django 5.2.4 on 2025-12-12 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backenddb', '0017_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='quantity',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
