# Generated by Django 5.2.4 on 2025-12-15 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backenddb', '0018_cart_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderconfirm',
            name='quantity',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
