# Generated by Django 5.2.4 on 2025-12-15 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backenddb', '0019_orderconfirm_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='quantity',
            field=models.CharField(default=1, max_length=10, null=True),
        ),
    ]
